services:
  bot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container
    environment:
      - DOMAIN=firefox
    command: bash -c "sleep 10 && python app/main.py"
    tty: true
    volumes:
      - "./app:/home/bot/app"
      - "./extracted_data:/home/bot/extracted_data"
    depends_on:
      - firefox

  firefox:
    image: selenium/standalone-firefox:125.0
    container_name: firefox_container
    ports:
      - "4444:4444"
      - "7900:7900"
  
  pgdb:
    image: postgres:15
    container_name: pgdb_container
    env_file:
      - config.env
    # environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres: